### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by PW999** [uken/newrelic-timing#8]
Hello,

thanks for the great plug-in, however, it took me quite a while to understand how it actually worked, so I would suggest adding the following items to your documentation:
- you must have the Newrelic snippet in your HTML. I think most Angular.js apps don't serve their HTML through JSP, so you must manually add the snippet from the Newrelic site to to head of your HTML page. 
- pageviews don't show up as "pageview" in Newrelic, instead they are logged as APM transactions
  ![2015-01-16 07_31_06-page views - cloud-hammer backend - new relic](https://cloud.githubusercontent.com/assets/8831154/5772365/c8dba356-9d51-11e4-9478-400f01c7f091.png)

I also made a little change to the newrelic-timing.js so that contact/view/1 and contact/view/2 (etc...) show up as /contact/view/\* (just as new relic would do in non-single-page sites)

``` (javascript)
this.NREUM.inlineHit(fragmentName.replace(/[0-9]+/g, "*"), 0, 0, 0, domTime, renderTime);
```

**Comment by pitr** [comment]
thanks @PW999, can you open a PR with your fixes?

**Comment by PW999** [comment]
Pull request made #9
